version: '3'
services:
  marks:  
    build: .
    shm_size: '1gb' 
    environment:
      - TZ=Europe/Paris
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
#    ports:
#      - 8071:8080
    volumes: 
      - /app/docker/run/MarksNotifier/data.txt:/home/data.txt
      - /app/docker/run/MarksNotifier/config.json:/home/config.json
